<a href="https://colab.research.google.com/github/trada177/Statement/blob/main/playing_w_tables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
database='database.sqlite'
conn=sqlite3.connect(database)
print("opened database successfully")

opened database successfully

In [3]:
import pandas as pd
tables=pd.read_sql_query("""SELECT * FROM sqlite_master WHERE type='table'""",conn)
tables

,type,name,tbl_name,rootpage,sql
0,table,Player,Player,2,CREATE TABLE [Player] (\n\t[Player_Id]\tintege...
1,table,Extra_Runs,Extra_Runs,3,CREATE TABLE [Extra_Runs] (\n\t[Match_Id]\tint...
2,table,Batsman_Scored,Batsman_Scored,7,CREATE TABLE [Batsman_Scored] (\n\t[Match_Id]\...
3,table,Batting_Style,Batting_Style,10,CREATE TABLE [Batting_Style] (\n\t[Batting_Id]...
4,table,Bowling_Style,Bowling_Style,11,CREATE TABLE [Bowling_Style] (\n\t[Bowling_Id]...
5,table,Country,Country,12,CREATE TABLE [Country] (\n\t[Country_Id]\tinte...
6,table,Season,Season,14,CREATE TABLE [Season] (\n\t[Season_Id]\tintege...
7,table,City,City,15,CREATE TABLE [City] (\n\t[City_Id]\tinteger NO...
8,table,Outcome,Outcome,16,CREATE TABLE [Outcome] (\n\t[Outcome_Id]\tinte...
9,table,Win_By,Win_By,17,CREATE TABLE [Win_By] (\n\t[Win_Id]\tinteger N...
10,table,Wicket_Taken,Wicket_Taken,18,CREATE TABLE [Wicket_Taken] (\n\t[Match_Id]\ti...
11,table,Venue,Venue,21,CREATE TABLE [Venue] (\n\t[Venue_Id]\tinteger ...
12,table,Extra_Type,Extra_Type,23,CREATE TABLE [Extra_Type] (\n\t[Extra_Id]\tint...
13,table,Out_Type,Out_Type,24,CREATE TABLE [Out_Type] (\n\t[Out_Id]\tinteger...
14,table,Toss_Decision,Toss_Decision,25,CREATE TABLE [Toss_Decision] (\n\t[Toss_Id]\ti...
15,table,Umpire,Umpire,26,CREATE TABLE [Umpire] (\n\t[Umpire_Id]\tintege...
16,table,Team,Team,27,CREATE TABLE [Team] (\n\t[Team_Id]\tinteger NO...
17,table,Ball_by_Ball,Ball_by_Ball,28,CREATE TABLE [Ball_by_Ball] (\n\t[Match_Id]\ti...
18,table,sysdiagrams,sysdiagrams,31,CREATE TABLE [sysdiagrams] (\n\t[name]\tnvarch...
19,table,sqlite_sequence,sqlite_sequence,32,"CREATE TABLE sqlite_sequence(name,seq)"
20,table,Match,Match,34,CREATE TABLE [Match] (\n\t[Match_Id]\tinteger ...
21,table,Rolee,Rolee,36,CREATE TABLE [Rolee] (\n\t[Role_Id]\tinteger N...
22,table,Player_Match,Player_Match,37,CREATE TABLE [Player_Match] (\n\t[Match_Id]\ti...

In [4]:
matches=pd.read_sql("""SELECT * FROM Match""",conn)
matches.head()

,Match_Id,Team_1,Team_2,Match_Date,Season_Id,Venue_Id,Toss_Winner,Toss_Decide,Win_Type,Win_Margin,Outcome_type,Match_Winner,Man_of_the_Match
0,335987,2,1,2008-04-18 00:00:00,1,1,2,1,1,140.0,1,1.0,2.0
1,335988,4,3,2008-04-19 00:00:00,1,2,3,2,1,33.0,1,3.0,19.0
2,335989,6,5,2008-04-19 00:00:00,1,3,5,2,2,9.0,1,6.0,90.0
3,335990,7,2,2008-04-20 00:00:00,1,4,7,2,2,5.0,1,2.0,11.0
4,335991,1,8,2008-04-20 00:00:00,1,5,8,2,2,5.0,1,1.0,4.0

Result

In [8]:
result1=pd.read_sql("""SELECT AVG(Win_Margin),Match_Winner FROM Match WHERE Season_Id==9 GROUP BY Match_Winner ORDER BY AVG(Win_Margin)""",conn)
result1.head()

   AVG(Win_Margin)  Match_Winner
0         4.666667            13
1         8.375000             1
2        10.428571             6
3        11.250000             4
4        14.600000            12

In [10]:
result2=pd.read_sql("""SELECT SUM(Win_Margin) FROM Match WHERE Season_Id==9""",conn)
result2.head()

   SUM(Win_Margin)
0              920